# TODO: Docs
[plots]
density_average = true
density_8 = true
density_observed = true
observed_8 = true
coverage = true
confidence = true
sankey_path = "test_data/READ_COUNTS.txt"
coverage_path = "test_data/A_HA_H3-coverage.txt"
heuristics_path = "test_data/A_PA-allAlleles.txt"
variants_path = "test_data/A_HA_H3-variants.txt"
pairing_stats_path = "test_data/A_PA-pairingStats.txt"
sqm_path = "test_data/A_NP-EXPENRD.sqm"

[output]
path = "out/"
width = 1200
height = 800

[constants]
# These are constants that affect the ranges of the heuristic plots. They are overridden in the configs for each IRMA module
min_aq = 24     # minimum average variant quality, does not apply to deletions
min_f = 0.008   # minimum frequency for single nucleotide variants
min_tcc = 100   # minimum non-ambiguous column coverage
min_conf = 0.80 # minimum confidence not machine error

# TODO: Make default color themes colorblind friendly/compliant
[density_average]
color = "#1f77b4"
stroke_width = 2.0
title = "Density of average allele quality"
xlabel = "Allele quality"
ylabel = "Density"

[density_8]
color = "#1f77b4"
stroke_width = 2.0
title = "Density of average allele quality to 8"
xlabel = "Allele quality"
ylabel = "Density" 

[density_observed]
color = "#1f77b4"
stroke_width = 2.0
title = "Density of average allele quality to 100%"
xlabel = "Observed frequency"
ylabel = "Density" 

[observed_8]
color = "#1f77b4"
stroke_width = 2.0
title = "Density of average allele quality to 100%"
xlabel = "Observed frequency"
ylabel = "Density" 

[coverage_histogram]
bins = 50   # from IRMA `heuristicDiagram.R`