# TODO: Docs
[targets]
list = ["A_HA_H3","A_MP","A_NA_N2","A_NP","A_NS","A_PA","A_PB1","A_PB2"]

[plot_toggles]
read_percentages = true
clustermap = true
heuristics = true
coverage = true

[input]
table_path = "test_tables/"
matrix_path = "test_matrices/"

[output]
path = "out/"

[constants]
# These are constants that affect the ranges of the heuristic plots. They are overridden in the configs for each IRMA module
min_aq = 24     # minimum average variant quality, does not apply to deletions
min_f = 0.008   # minimum frequency for single nucleotide variants
min_tcc = 100   # minimum non-ambiguous column coverage
min_conf = 0.80 # minimum confidence not machine error

[coverage_options]
variant_color = "nucleotide" # either "nucleotide" for original configuration, or "frequency" for possible change

[percent_options]
viz_option = "pie" # either "sankey" or "pie"
paired = true

[cluster_options]
cluster_option = "clustermap" # either "clustermap" or "heatmap"